version: '3'
services:
  mango1:
    image: flask-server
    environment:
      - APP=mango
    ports:
      - "8081:5000"

  mango2:
    image: flask-server
    environment:
      - APP=mango
    ports:
      - "8082:5000"

  apple1:
    image: flask-server
    environment:
      - APP=apple
    ports:
      - "9081:5000"

  apple2:
    image: flask-server
    environment:
      - APP=apple
    ports:
      - "9082:5000"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24